# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2d9d22b90f87297e9d608dbd624b39891ba2d29687e538f62bfd0921c95ee5b300599db3257d7936a5106730053f8d693c199e9f79f446938e95da8a9141586f

test:
  secret_key_base: bbfaa7b71da4fea6b15fefd07bec66051e23f27e80bf3c700bb7b11ff8b2672f180073d850686902dea0d4a90df265d98aacc06ced7cb4737f242883d480d18e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
